### ISSUE TITLE
Two requested features

### ISSUE THREAD

**Issue by florianmalard** [GOTIT-DEV/GOTIT#22]
Dear Louis and Philippe,

Two feature requests below:

Feature request 1 : In the read-only mode, users should have accessed to the followings :

a) To the button “Export to CSV file” in the content list. For the moment, this button does not appear in the read-only mode.
b) To the Querybuilder

Feature request 2: In the site form, both in the “create, edit and show” modes, the tool “Show nearby sites” is incomplete.
On the map, when clicking on a site label (red triangle) the code of the site should appear on the label, with a link to the formular of that site and the possibility to come back to the map (as in the species search bundle).

All the best,

Florian

**Comment by lsdch** [comment]
Remaining item is fixed by 821f231c
